"""empty message

Revision ID: 1574ffcf1834
Revises: 2b6d1e9b1e5e
Create Date: 2024-01-21 01:24:34.560481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1574ffcf1834'
down_revision = '2b6d1e9b1e5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publish', sa.Boolean(), nullable=True, server_default="false"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_column('publish')

    # ### end Alembic commands ###
