"""empty message

Revision ID: 2bcc296a15b6
Revises: 527ea632f152
Create Date: 2024-01-21 02:26:07.448906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bcc296a15b6'
down_revision = '527ea632f152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_publish', sa.Boolean(), nullable=True, server_default="false"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_column('is_publish')

    # ### end Alembic commands ###
