"""chore: add isActive field to the campaign table and user_status to User table

Revision ID: 740ff705c401
Revises: 
Create Date: 2023-02-03 07:52:57.794755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '740ff705c401'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isActive', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_status', sa.String(length=20), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('user_status')

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_column('isActive')

    # ### end Alembic commands ###
