"""empty message

Revision ID: 97465866ed55
Revises: 2bcc296a15b6
Create Date: 2024-01-23 05:16:11.465072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97465866ed55'
down_revision = '2bcc296a15b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
