"""chore: initial migration

Revision ID: 86e1cb48e2e3
Revises: 
Create Date: 2022-08-03 16:33:58.364489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86e1cb48e2e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contact', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('contact', 'subject',
               existing_type=sa.VARCHAR(),
               nullable=<function false at 0x0000013554FF1750>)
    op.alter_column('contact', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=<function false at 0x0000013554FF1750>)
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('contact', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('contact', 'subject',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('contact', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###

